server:
  port: 1472

spring:
  datasource:
    url: ${POSTGRES_URL:}
    username: ${POSTGRES_USERNAME:}
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: prod

telegram:
  notifier-bot:
    username: ${TELEGRAM_BOT_USERNAME:}
    token: ${TELEGRAM_BOT_TOKEN:}
    webHookPath: ${TELEGRAM_WEB_HOOK_PATH:}

redisson:
  database: ${REDIS_DB:0}
  url: ${REDIS_HOST:}:${REDIS_PORT:}
  password: ${REDIS_PASSWORD:}

