# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Redeploy oracle server
on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_PK }}
          port: 22
          script: |
            cd github/platform-notifier/platform-notifier && ./gradlew bootJar && sudo docker build -t platform-notifier . && sudo docker stop platform-notifier ; sudo docker rm platform-notifier ; sudo docker run --name platform-notifier -p 1472:1472 -d platform-notifier
